# Generated by Django 5.0.6 on 2024-06-13 14:44

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='username', unique=True)),
                ('age', models.PositiveIntegerField()),
                ('pic', models.ImageField(upload_to='images/')),
                ('institution_name', models.CharField(max_length=254)),
                ('degree', models.CharField(max_length=254)),
                ('field', models.CharField(max_length=254)),
                ('skills', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
